server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 0.01
  maxMoney: 9999
  description: You should pay more than ${limit.minMoney} RMB,but no more than ${limit.maxMoney} RMB.